apiVersion: v1
kind: Service
metadata:
  # Metadata for the React service
  name: react-service
  labels:
    app: react
    tier: front-end
spec:
  # Must match the labels of POD
  selector:
    app: react
    tier: front-end
  # Type of Service
  type: NodePort
  # Specifications for the service
  ports: 
    # Service - Virtual Server port
    - port: 3000
    # POD port
      targetPort: 3000
    # Host port
      nodePort: 30000