apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  # Metadata about the PVC
  name: mysql-pvc
  labels:
    app: mysql
    tier: database
spec:
  # Mode of the PVC
  # Generally means that only one POD can write to the storage at a time
  accessModes:
    - ReadWriteOnce
  # Resources allocated to the PVC
  resources:
    requests:
      storage: 1Gi
  